### ISSUE TITLE
Wallet GUI only starts in low graphics mode

### ISSUE THREAD

**Issue by Staz1st** [monerov/monerov#1]
Hi happy to have a monerov wallet available.
I've installed the WINDOWS 64bit GUI on a win10 64bit pc on an external drive.
The wallet will close itself immediately after starting the _monerov-wallet-gui.exe_.
When started from _start-low-graphics-mode.bat_ the wallet seems to work.
Any suggestion?
[monerov-wallet-gui.log](https://github.com/monerov/monerov/files/1985536/monerov-wallet-gui.log)

**Comment by miltonf** [comment]
Please open the issue in the GUI repo.
