### ISSUE TITLE
Problem with payout to clinet 

### ISSUE THREAD

**Issue by rut78HR** [monerov/monerov#11]
Hello ..  I have identical problem described here https://github.com/monero-project/monero/issues/3806
Monero team release patch to fix these so could u implement same in monerov ?

**Comment by rut78HR** [comment]
no dev team here .. ? :)

**Comment by instanceme** [comment]
A new migration that will include several patches will be up soon including speeding up `get_output_distribution`.

**Comment by rut78HR** [comment]
tnx for info ! :)

**Comment by rut78HR** [comment]
pls when can expect these patches .. ??
