### ISSUE TITLE
new patches and improvments ? 

### ISSUE THREAD

**Issue by rut78HR** [monerov/monerov#14]
Hello 
whether and when to be seen something like that?

**Comment by vanfactory** [comment]
Very soon there will be a major update for both the daemon and for the gui.

**Comment by jenniferberger** [comment]
Where is the 'Full-time development team.' (quote from https://monerov.org/#different) working?
Dumping a huge changeset on github only when there is 'major update' does not make audit simple and contributions impossible.

**Comment by vanfactory** [comment]
Updates will happen regularly to the git repository in a separate branch. These major updates occur right now because they are necessary to close a big gap. closing for now

**Comment by rut78HR** [comment]
Where is that separate branch ?? and still no updates to git !
