### ISSUE TITLE
Raspberry PI - undefined reference / collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by theMoe** [monerov/monerov#24]
Hi,

I tried to build a monerov node on a Raspberry PI 3 B+ with all the steps explained in the readme file.

I always get errors like this:

[ 95%] Building CXX object src/daemon/CMakeFiles/daemon.dir/rpc_command_executor.cpp.o^M
...
[ 95%] Linking CXX executable ../../bin/monerovd
...
/usr/lib/gcc/arm-linux-gnueabihf/6/../../../arm-linux-gnueabihf/libzmq.a(src_libzmq_la-pgm_socket.o): In function `zmq::pgm_socket_t::~pgm_socket_t()':
(.text+0x20f0): undefined reference to `pgm_close'
collect2: error: ld returned 1 exit status
src/daemon/CMakeFiles/daemon.dir/build.make:289: die Regel für Ziel „bin/monerovd“ scheiterte
make[3]: *** [bin/monerovd] Fehler 1
make[3]: Verzeichnis „/home/pi/monerov/monerov/build/release“ wird verlassen
CMakeFiles/Makefile2:3017: die Regel für Ziel „src/daemon/CMakeFiles/daemon.dir/all“ scheiterte
make[2]: *** [src/daemon/CMakeFiles/daemon.dir/all] Fehler 2
make[2]: Verzeichnis „/home/pi/monerov/monerov/build/release“ wird verlassen
Makefile:138: die Regel für Ziel „all“ scheiterte
make[1]: *** [all] Fehler 2
make[1]: Verzeichnis „/home/pi/monerov/monerov/build/release“ wird verlassen
Makefile:82: die Regel für Ziel „release-static-linux-armv7“ scheiterte
make: *** [release-static-linux-armv7] Fehler 2

Can someone help me with this?

Thanks!

Moe

**Comment by mataragama** [comment]
which version of os are you using? On raspbian 9. Works fine.
Have installed libpgm and libzmq?

**Comment by theMoe** [comment]
I use 
Raspbian Stretch Lite
Version: November 2018
Release date: 2018-11-13
Kernel version: 4.14

And used this command:

sudo apt-get install -y  build-essential cmake pkg-config libboost-all-dev libssl-dev libzmq3-dev libunbound-dev libsodium-dev libminiupnpc-dev libunwind8-dev liblzma-dev libreadline6-dev libldns-dev libexpat1-dev libgtest-dev doxygen graphviz

sudo apt-get install libpcsclite-dev

I didn’t see libpgm in the readme document. For libzmq I installed libzmq3-dev. Is this correct?

**Comment by theMoe** [comment]
Are there any active developers who can help with this issue?

**Comment by miltonf** [comment]
Do you have libpgm and/or libnorm installed? try installing `libpgm-dev` .

**Comment by theMoe** [comment]
I did:

sudo apt-get install -y libpgm-dbg

But then I try -dev

**Comment by theMoe** [comment]
I installed it, but I can't get it compiled. Whenn it reaches 87% the memory and the swapfile runs full. And then the PI "crashes" and needs to be rebooted (with power off on).

Is there a log file I can provided, that would help to find the problem?

**Comment by theMoe** [comment]
@miltonf Is there way we can chat via slack or discord?

**Comment by theMoe** [comment]
Compiling ende again after 87%

`[ 87%] Building CXX object src/wallet/CMakeFiles/obj_wallet.dir/wallet2.cpp.o
...
/usr/include/c++/6/bits/stl_algo.h:1920:77: note: parameter passing for argument of type ‘__gnu_cxx::__normal_iterator<std::tuple<long long unsigned int, crypto::public_key, rct::key>*, std::vector<std::tuple<long long unsigned int, crypto::public_key, rct::key> > >’ will change in GCC 7.1
/usr/include/c++/6/bits/stl_algo.h:1920:77: note: parameter passing for argument of type ‘__gnu_cxx::__normal_iterator<std::tuple<long long unsigned int, crypto::public_key, rct::key>*, std::vector<std::tuple<long long unsigned int, crypto::public_key, rct::key> > >’ will change in GCC 7.1
/usr/include/c++/6/bits/stl_algo.h:1951:4: note: parameter passing for argument of type ‘__gnu_cxx::__normal_iterator<std::tuple<long long unsigned int, crypto::public_key, rct::key>*, std::vector<std::tuple<long long unsigned int, crypto::public_key, rct::key> > >’ will change in GCC 7.1
    std::__introsort_loop(__cut, __last, __depth_limit, __comp);
    ^~~
In file included from /usr/include/boost/asio/detail/reactive_socket_service_base.hpp:32:0,
                 from /usr/include/boost/asio/detail/reactive_socket_service.hpp:34,
                 from /usr/include/boost/asio/datagram_socket_service.hpp:30,
                 from /usr/include/boost/asio/basic_datagram_socket.hpp:21,
                 from /usr/include/boost/asio.hpp:21,
                 from /home/pi/monerov/monerov/contrib/epee/include/net/net_helper.h:36,
                 from /home/pi/monerov/monerov/contrib/epee/include/net/http_client.h:41,
                 from /home/pi/monerov/monerov/src/wallet/wallet2.h:46,
                 from /home/pi/monerov/monerov/src/wallet/wallet2.cpp:44:
/usr/include/boost/asio/detail/reactive_socket_send_op.hpp: In static member function ‘static void boost::asio::detail::reactive_socket_send_op<ConstBufferSequence, Handler>::do_complete(boost::asio::detail::io_service_impl*, boost::asio::detail::operation*, const boost::system::error_code&, std::size_t) [with ConstBufferSequence = boost::asio::mutable_buffers_1; Handler = boost::asio::detail::write_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, boost::asio::ssl::detail::io_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::ssl::detail::shutdown_op, boost::lambda::lambda_functor<boost::lambda::lambda_functor_base<boost::lambda::other_action<boost::lambda::assignment_action>, boost::tuples::tuple<boost::lambda::lambda_functor<boost::lambda::identity<boost::system::error_code&> >, boost::lambda::lambda_functor<boost::lambda::placeholder<1> >, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type> > > > >]’:
/usr/include/boost/asio/detail/reactive_socket_send_op.hpp:110:3: internal compiler error: Speicherzugriffsfehler
   }
   ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
src/wallet/CMakeFiles/obj_wallet.dir/build.make:62: die Regel für Ziel „src/wallet/CMakeFiles/obj_wallet.dir/wallet2.cpp.o“ scheiterte
make[3]: *** [src/wallet/CMakeFiles/obj_wallet.dir/wallet2.cpp.o] Fehler 1
make[3]: Verzeichnis „/home/pi/monerov/monerov/build/release“ wird verlassen
CMakeFiles/Makefile2:2258: die Regel für Ziel „src/wallet/CMakeFiles/obj_wallet.dir/all“ scheiterte
make[2]: *** [src/wallet/CMakeFiles/obj_wallet.dir/all] Fehler 2
make[2]: Verzeichnis „/home/pi/monerov/monerov/build/release“ wird verlassen
Makefile:138: die Regel für Ziel „all“ scheiterte
make[1]: *** [all] Fehler 2
make[1]: Verzeichnis „/home/pi/monerov/monerov/build/release“ wird verlassen
Makefile:57: die Regel für Ziel „release“ scheiterte
make: *** [release] Fehler 2`

**Comment by theMoe** [comment]
I didn’t change anything but after n times the node compiled. I hadn’t had the time to double check, if it works but I didn’t get an error...
