### ISSUE TITLE
only 11 decimals displayed

### ISSUE THREAD

**Issue by krtschmr** [monerov/monerov#3]
is it a display issue?

![image](https://user-images.githubusercontent.com/13366714/40013999-747e5862-57d9-11e8-8ae3-b1cca66ded6a.png)

**Comment by miltonf** [comment]
I think this issue belongs to the gui repo: https://github.com/monerov/monerov-gui/. Nevertheless, there doesn't seem to be anything wrong.

**Comment by krtschmr** [comment]
@miltonf the CLI shows 0.10000000000

so that are also just 11 decimal rather then 12. basically they moved the dot on the display just more to the right to make it x10 and didn't airdropped outputs or something (which is tricky with private blockchain).

apparently this issue is not GUI or CLI related, it's core related.

i can't find anything where they have some x10 in the code. can u point me to some LOC?

**Comment by kriptontr** [comment]
recieving same amount XMV with the balance of XMR explains this. 
just approve you did 10x airdrop by lowering resolution to 10^12 to 10^11 or not ?

**Comment by vanfactory** [comment]
Yes. That is the smart and only way to accomplish it. The 10x was changed in core definition and in multiple locations, including modifications for the tests and rpc wallet to accommodate the change.
